### ISSUE TITLE
[Feature request] Manual search tags

### ISSUE THREAD

**Issue by vatterspun** [ator-dev/mark-my-search#3]
I don't know of another program that will do this so I wondered if this might be worth chasing ...

**Current behavior**

In order to launch the keyword search, you need to start in a view like DuckDuckGo and then click through to a potential destination page.  

Why manual?  Sometimes I'm trying to run a search on a location that doesn't connect from a search page.  Would still like to have the highlighted terms available.

**Requested behavior**

Manually launch the search function for a given page either through the Mark My Search menu icon or some kind of hotkey like CTRL+SHIFT+M or similar.

**Comment by ator-dev** [comment]
That was actually partially implemented at some point through a context menu item when text is selected, but looks like clicking it stopped working at some point. I definitely agree that this would be very useful, and for me it somehow feels better to add 'search terms' than open the default search (;

I think having it available as a 'blank' search from the icon would be a good idea (and potentially a menu item when no text is highlighted). As for the shortcut that would be great as well - as an avid hotkey user I'm ashamed of the lack of shortcuts for many common actions, and these will certainly be implemented in the future.

**Comment by vatterspun** [comment]
Cool, very glad that was useful

**Comment by ator-dev** [comment]
All discussed features implemented in commit 81a07cf8be03a51b613061562d2d3937cb2cf971
Note that these are not yet fully tested.

**Comment by vatterspun** [comment]
Verified that this was added, thanks.  Works well above what I was asking for / expecting.  Big thanks.

**Comment by ator-dev** [comment]
Thanks for testing, glad you like the new functions!
